"""create units table with auto-creation on property

Revision ID: 3d80f744c87b
Revises: 7e46df18905d
Create Date: 2026-02-14 14:46:05.917573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d80f744c87b'
down_revision: Union[str, Sequence[str], None] = '7e46df18905d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('rent_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('occupied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
    op.create_index(op.f('ix_units_property_id'), 'units', ['property_id'], unique=False)
    op.create_index(op.f('ix_units_unit_number'), 'units', ['unit_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_units_unit_number'), table_name='units')
    op.drop_index(op.f('ix_units_property_id'), table_name='units')
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.drop_table('units')
    # ### end Alembic commands ###
