"""add events table

Revision ID: 74293b205e7d
Revises: 8aa090efade0
Create Date: 2026-02-13 22:53:00.455022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74293b205e7d'
down_revision: Union[str, Sequence[str], None] = '8aa090efade0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('approval_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_approval_id'), 'events', ['approval_id'], unique=False)
    op.create_index(op.f('ix_events_due_date'), 'events', ['due_date'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_property_id'), 'events', ['property_id'], unique=False)
    op.create_index(op.f('ix_events_ticket_id'), 'events', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_ticket_id'), table_name='events')
    op.drop_index(op.f('ix_events_property_id'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_due_date'), table_name='events')
    op.drop_index(op.f('ix_events_approval_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
