"""add maintenance_category column to tickets

Revision ID: 7e46df18905d
Revises: a0d0de1140fc
Create Date: 2026-02-14 14:11:18.837147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e46df18905d'
down_revision: Union[str, Sequence[str], None] = 'a0d0de1140fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('maintenance_category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'maintenance_category')
    # ### end Alembic commands ###
