"""add property_id foreign key to approvals

Revision ID: 8aa090efade0
Revises: c5aeed6ea745
Create Date: 2026-02-13 22:11:44.110650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa090efade0'
down_revision: Union[str, Sequence[str], None] = 'c5aeed6ea745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('property_id', sa.BigInteger(), nullable=False))
    op.drop_index(op.f('ix_approvals_property'), table_name='approvals')
    op.create_index(op.f('ix_approvals_property_id'), 'approvals', ['property_id'], unique=False)
    op.create_foreign_key(None, 'approvals', 'properties', ['property_id'], ['id'])
    op.drop_column('approvals', 'property')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('property', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.drop_index(op.f('ix_approvals_property_id'), table_name='approvals')
    op.create_index(op.f('ix_approvals_property'), 'approvals', ['property'], unique=False)
    op.drop_column('approvals', 'property_id')
    # ### end Alembic commands ###
