"""add occupancy column to properties table

Revision ID: a0d0de1140fc
Revises: 74293b205e7d
Create Date: 2026-02-14 00:05:37.811930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d0de1140fc'
down_revision: Union[str, Sequence[str], None] = '74293b205e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server default of 0
    op.add_column('properties', sa.Column('occupancy', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'occupancy')
    # ### end Alembic commands ###
