"""expand tickets fields

Revision ID: b1a39aebe876
Revises: 61cbeea623af
Create Date: 2026-02-12 19:03:52.711648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1a39aebe876'
down_revision: Union[str, Sequence[str], None] = '61cbeea623af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('property', sa.String(), nullable=False))
    op.add_column('tickets', sa.Column('type', sa.String(), nullable=False))
    op.add_column('tickets', sa.Column('issue', sa.String(), nullable=False))
    op.add_column('tickets', sa.Column('assigned_to', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('tickets', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('tickets', 'updated_at')
    op.drop_column('tickets', 'sla_due_at')
    op.drop_column('tickets', 'assigned_to')
    op.drop_column('tickets', 'issue')
    op.drop_column('tickets', 'type')
    op.drop_column('tickets', 'property')
    # ### end Alembic commands ###
