"""add property_id foreign key to tickets

Revision ID: c5aeed6ea745
Revises: df5c667b7bec
Create Date: 2026-02-13 17:20:50.389956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5aeed6ea745'
down_revision: Union[str, Sequence[str], None] = 'df5c667b7bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('property_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_tickets_property_id'), 'tickets', ['property_id'], unique=False)
    op.create_foreign_key(None, 'tickets', 'properties', ['property_id'], ['id'])
    op.drop_column('tickets', 'property')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('property', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_property_id'), table_name='tickets')
    op.drop_column('tickets', 'property_id')
    # ### end Alembic commands ###
